# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "522fbfa5df57c9ebb520dce112b81361"
name = "post-purchase"
application_url = "https://post-purchase.benjmeyer02.workers.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "devs-9802.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://post-purchase.benjmeyer02.workers.dev/api/auth" ]
